name: mdict_reader
description: A dart library for reading mdict files. support MDX/MDD file formats.
version: 1.1.0
homepage: https://github.com/qingshan/mdict_reader

environment:
  sdk: '>=2.12.1 <3.0.0'

dependencies:
  args: ^2.3.1
  xml: ^6.0.1
  pointycastle: ^3.6.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
